events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # FastAPI — en Swarm, 'fastapi' resuelve via VIP
    # al pool de instancias activas (round-robin automático)
    upstream fastapi {
        server fastapi:8000;
    }

    # MinIO API — balanceo manual entre los 3 nodos
    upstream minio {
        server minio1:9000;
        server minio2:9000;
        server minio3:9000;
    }

    server {
        listen 80;

        # API — proxeado a FastAPI
        location /api/ {
            proxy_pass http://fastapi/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 60s;
        }

        # Frontend Angular — archivos estáticos compilados
        # Angular usa routing del lado del cliente, por eso el fallback a index.html
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
